version: '3.2'

services:
  mysql:
    ports:
      - 3306:3306
    image: library/mysql:8.0.22
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=database

  web:
    image: nginx:latest
    ports:
      - 2080:2080
      - 3080:3080
      - 4080:4080
      - 5080:5080
    volumes:
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/local.conf
    volumes_from:
      - app
    links:
      - php
    entrypoint: nginx -g 'daemon off;'
    working_dir: /app

  app:
    build:
      context: ./
      dockerfile: ./docker/composer/Dockerfile
    ports:
      - 82:8082
    volumes:
      - ./app:/app
      - ./docker/composer/entrypoint.sh:/entrypoint.sh
    tty: true
    entrypoint: /entrypoint.sh

  php:
    ports:
      - 9000
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - app
      - mysql
    volumes:
      - ./docker/php/cron:/cron
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    volumes_from:
      - app
    links:
      - mysql
    env_file:
      - ./app/.env

  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 6080
    ports:
      - 6080:8080
    volumes_from:
      - app
    environment:
      API_URL: http://localhost:5080

volumes:
  app: